from __future__ import annotations

from .neuron_base import Neuron
from .micro_neurons import MICRO_NEURONS
from .neurons_adaptive import (
    AdaptiveGrowthBootstrapNeuron,
    AntiOverfitFilterNeuron,
    CompoundingDriveNeuron,
    ConfidenceMemoryNeuron,
    DailyCoachNeuron,
    ExplorationDriveNeuron,
    LossReviewNeuron,
    MarketMemoryBridgeNeuron,
    OpportunityCompressionNeuron,
    PairMemoryResonanceNeuron,
    ProfitReplayNeuron,
    RegimeMutationNeuron,
    SelfTrainingLoopNeuron,
    SelfReflectionNeuron,
    SurvivalInstinctNeuron,
)
from .neurons_complex import (
    BollingerElasticityNeuron,
    CCIImpulseNeuron,
    CorrelationImpulseNeuron,
    DecisionLatencyNeuron,
    DeltaFlowNeuron,
    FailedAuctionNeuron,
    LevelCompressionNeuron,
    LiquidityPocketNeuron,
    NarrativePressureNeuron,
    PrimeWindowNeuron,
    RegimeCoherenceNeuron,
    RiskCompressionNeuron,
    SessionRotationMapNeuron,
    StochasticPhaseNeuron,
    VWAPElasticityNeuron,
)
from .neurons_core import (
    HigherTimeframeBiasNeuron,
    InputReaderNeuron,
    KeyLevelsNeuron,
    LiquidityContextNeuron,
    MarketRegimeNeuron,
    MissionGuardNeuron,
    PersonaCoreNeuron,
    StructureMapperNeuron,
    VolatilityEngineNeuron,
    VolumeMomentumNeuron,
)
from .neurons_market_specific import (
    AssetClassifierNeuron,
    CorrelationContextNeuron,
    CryptoMicrostructureNeuron,
    ForexSessionQualityNeuron,
    LeverageGuardNeuron,
    MeanReversionPressureNeuron,
    PositionSizingNeuron,
    SessionContextNeuron,
    SpreadSlippageGuardNeuron,
    TrendContinuationNeuron,
    TrendStrengthNeuron,
    RangeFadeNeuron,
)
from .neurons_output import OutputFormatterNeuron, VerdictGateNeuron
from .neurons_pro import (
    AccountHeatNeuron,
    AsymmetryNeuron,
    BreakoutQualityNeuron,
    CandleAnatomyNeuron,
    ConvictionCalibrationNeuron,
    DrawdownGuardNeuron,
    ExecutionLocationNeuron,
    OrderbookPressureNeuron,
    RecoveryModeNeuron,
    ReferenceLevelMemoryNeuron,
    TimeframeStyleCompatibilityNeuron,
    TrapDetectionNeuron,
)
from .neurons_risk import EventSentimentGuardNeuron, NoTradeFilterNeuron, RiskBudgetNeuron, StopLossArchitectNeuron, TargetEngineNeuron
from .neurons_setup import BreakoutRetestNeuron, ConfluenceScoreNeuron, LongSetupNeuron, PullbackReversalNeuron, ShortSetupNeuron


ALL_NEURONS: list[Neuron] = [
    PersonaCoreNeuron(),
    MissionGuardNeuron(),
    InputReaderNeuron(),
    AssetClassifierNeuron(),
    AdaptiveGrowthBootstrapNeuron(),
    SelfTrainingLoopNeuron(),
    SessionContextNeuron(),
    TimeframeStyleCompatibilityNeuron(),
    MarketRegimeNeuron(),
    HigherTimeframeBiasNeuron(),
    StructureMapperNeuron(),
    PairMemoryResonanceNeuron(),
    MarketMemoryBridgeNeuron(),
    ProfitReplayNeuron(),
    RegimeMutationNeuron(),
    ExplorationDriveNeuron(),
    NarrativePressureNeuron(),
    SessionRotationMapNeuron(),
    StochasticPhaseNeuron(),
    BollingerElasticityNeuron(),
    CCIImpulseNeuron(),
    DeltaFlowNeuron(),
    VWAPElasticityNeuron(),
    KeyLevelsNeuron(),
    LevelCompressionNeuron(),
    FailedAuctionNeuron(),
    LiquidityPocketNeuron(),
    RegimeCoherenceNeuron(),
    PrimeWindowNeuron(),
    CorrelationImpulseNeuron(),
    DecisionLatencyNeuron(),
    OpportunityCompressionNeuron(),
    ReferenceLevelMemoryNeuron(),
    LiquidityContextNeuron(),
    VolumeMomentumNeuron(),
    VolatilityEngineNeuron(),
    TrendStrengthNeuron(),
    MeanReversionPressureNeuron(),
    ForexSessionQualityNeuron(),
    CryptoMicrostructureNeuron(),
    OrderbookPressureNeuron(),
    SpreadSlippageGuardNeuron(),
    CandleAnatomyNeuron(),
    BreakoutQualityNeuron(),
    TrapDetectionNeuron(),
    LongSetupNeuron(),
    ShortSetupNeuron(),
    BreakoutRetestNeuron(),
    PullbackReversalNeuron(),
    TrendContinuationNeuron(),
    RangeFadeNeuron(),
    ExecutionLocationNeuron(),
    ConfluenceScoreNeuron(),
    DrawdownGuardNeuron(),
    CompoundingDriveNeuron(),
    SurvivalInstinctNeuron(),
    RiskBudgetNeuron(),
    RecoveryModeNeuron(),
    PositionSizingNeuron(),
    RiskCompressionNeuron(),
    AccountHeatNeuron(),
    LeverageGuardNeuron(),
    StopLossArchitectNeuron(),
    TargetEngineNeuron(),
    AsymmetryNeuron(),
    *MICRO_NEURONS,
    EventSentimentGuardNeuron(),
    CorrelationContextNeuron(),
    NoTradeFilterNeuron(),
    AntiOverfitFilterNeuron(),
    ConvictionCalibrationNeuron(),
    ConfidenceMemoryNeuron(),
    LossReviewNeuron(),
    DailyCoachNeuron(),
    SelfReflectionNeuron(),
    OutputFormatterNeuron(),
    VerdictGateNeuron(),
]


BASE_VISUAL_META: dict[str, dict[str, str]] = {
    "neuron01_persona_core": {"title": "Persona Core", "group": "core", "stage": "core", "description": "Identity layer untuk brain trading."},
    "neuron02_mission_guard": {"title": "Mission Guard", "group": "core", "stage": "core", "description": "Misi utama: lindungi modal lebih dulu."},
    "neuron03_input_reader": {"title": "Input Reader", "group": "core", "stage": "core", "description": "Membaca kualitas data input."},
    "neuron04_asset_classifier": {"title": "Asset Classifier", "group": "core", "stage": "core", "description": "Membedakan crypto dan forex."},
    "neuron47_adaptive_growth_bootstrap": {"title": "Adaptive Bootstrap", "group": "adaptive", "stage": "adaptive", "description": "Membuka growth profile dari histori pair dan sektor."},
    "neuron73_self_training_loop": {"title": "Self Training Loop", "group": "adaptive", "stage": "adaptive", "description": "Membaca replay profit/loss harian untuk pair dan market."},
    "neuron05_session_context": {"title": "Session Context", "group": "core", "stage": "core", "description": "Membaca session dan kualitas likuiditas."},
    "neuron35_timeframe_style_compatibility": {"title": "TF/Style Match", "group": "core", "stage": "core", "description": "Menguji kecocokan timeframe dan style."},
    "neuron04_market_regime": {"title": "Market Regime", "group": "market", "stage": "market", "description": "Klasifikasi fase market."},
    "neuron05_higher_timeframe_bias": {"title": "HTF Bias", "group": "market", "stage": "market", "description": "Bias timeframe besar."},
    "neuron06_structure_mapper": {"title": "Structure Mapper", "group": "market", "stage": "market", "description": "Membaca arah struktur market."},
    "neuron48_pair_memory_resonance": {"title": "Pair Memory Resonance", "group": "adaptive", "stage": "adaptive", "description": "Sinkronisasi histori pair dengan struktur saat ini."},
    "neuron49_market_memory_bridge": {"title": "Market Memory Bridge", "group": "adaptive", "stage": "adaptive", "description": "Jembatan konteks sektor saat pair masih tipis."},
    "neuron74_profit_replay": {"title": "Profit Replay", "group": "adaptive", "stage": "adaptive", "description": "Menguatkan arah yang terbukti sehat dari replay hasil profit."},
    "neuron50_regime_mutation": {"title": "Regime Mutation", "group": "adaptive", "stage": "adaptive", "description": "Mengubah agresivitas sesuai cycle dan regime."},
    "neuron51_exploration_drive": {"title": "Exploration Drive", "group": "adaptive", "stage": "adaptive", "description": "Memberi ruang eksplorasi ringan saat baseline masih tumbuh."},
    "neuron58_narrative_pressure": {"title": "Narrative Pressure", "group": "cortex", "stage": "cortex", "description": "Tekanan narasi market terhadap arah trade."},
    "neuron59_session_rotation_map": {"title": "Session Rotation", "group": "cortex", "stage": "cortex", "description": "Sinkronisasi dorong session dan style entry."},
    "neuron60_stochastic_phase": {"title": "Stochastic Phase", "group": "cortex", "stage": "cortex", "description": "Fase stochastic untuk continuation sehat."},
    "neuron61_bollinger_elasticity": {"title": "Bollinger Elasticity", "group": "cortex", "stage": "cortex", "description": "Elastisitas band untuk continuation atau fade."},
    "neuron62_cci_impulse": {"title": "CCI Impulse", "group": "cortex", "stage": "cortex", "description": "Impuls CCI terhadap bias aktif."},
    "neuron63_delta_flow": {"title": "Delta Flow", "group": "cortex", "stage": "cortex", "description": "Arah delta volume untuk tekanan tape."},
    "neuron64_vwap_elasticity": {"title": "VWAP Elasticity", "group": "cortex", "stage": "cortex", "description": "Kedekatan harga ke VWAP untuk entry efisien."},
    "neuron07_key_levels": {"title": "Key Levels", "group": "market", "stage": "market", "description": "Support dan resistance utama."},
    "neuron65_level_compression": {"title": "Level Compression", "group": "cortex", "stage": "cortex", "description": "Kompresi support-resistance menjelang ledakan."},
    "neuron66_failed_auction": {"title": "Failed Auction", "group": "cortex", "stage": "cortex", "description": "Tanda gagal lelang dari wick dan posisi range."},
    "neuron67_liquidity_pocket": {"title": "Liquidity Pocket", "group": "cortex", "stage": "cortex", "description": "Pocket likuiditas sehat dekat level penting."},
    "neuron68_regime_coherence": {"title": "Regime Coherence", "group": "cortex", "stage": "cortex", "description": "Keselarasan bias, struktur, dan regime."},
    "neuron69_prime_window": {"title": "Prime Window", "group": "cortex", "stage": "cortex", "description": "Jendela market yang paling ideal untuk eksekusi."},
    "neuron70_correlation_impulse": {"title": "Correlation Impulse", "group": "cortex", "stage": "cortex", "description": "Tailwind/headwind dari korelasi lintas aset."},
    "neuron72_decision_latency": {"title": "Decision Latency", "group": "cortex", "stage": "cortex", "description": "Menahan trade saat keputusan belum matang."},
    "neuron52_opportunity_compression": {"title": "Opportunity Compression", "group": "adaptive", "stage": "adaptive", "description": "Mengutamakan entry yang rapat ke level penting."},
    "neuron36_reference_level_memory": {"title": "Reference Memory", "group": "market", "stage": "market", "description": "Previous/session high-low memory."},
    "neuron08_liquidity_context": {"title": "Liquidity Context", "group": "market", "stage": "market", "description": "Sweep, trap, dan liquidity map."},
    "neuron09_volume_momentum": {"title": "Volume Momentum", "group": "market", "stage": "market", "description": "Tenaga dorong market."},
    "neuron10_volatility_engine": {"title": "Volatility Engine", "group": "market", "stage": "market", "description": "Membaca ekspansi dan noise."},
    "neuron13_trend_strength": {"title": "Trend Strength", "group": "pro", "stage": "pro", "description": "Kekuatan trend dengan ADX dan EMA."},
    "neuron14_mean_reversion_pressure": {"title": "Mean Reversion", "group": "pro", "stage": "pro", "description": "Tekanan balik ke mean."},
    "neuron15_forex_session_quality": {"title": "Forex Session Q", "group": "pro", "stage": "pro", "description": "Filter session khusus forex."},
    "neuron16_crypto_microstructure": {"title": "Crypto Microstruct", "group": "pro", "stage": "pro", "description": "Funding, OI, dan weekend crypto."},
    "neuron37_orderbook_pressure": {"title": "Orderbook Pressure", "group": "pro", "stage": "pro", "description": "Imbalance dan liquidity score."},
    "neuron17_spread_slippage_guard": {"title": "Spread/Slippage", "group": "pro", "stage": "pro", "description": "Friction cost execution."},
    "neuron38_candle_anatomy": {"title": "Candle Anatomy", "group": "pro", "stage": "pro", "description": "Body, wick, dan close anatomy."},
    "neuron39_breakout_quality": {"title": "Breakout Quality", "group": "pro", "stage": "pro", "description": "Kualitas breakout atau breakdown."},
    "neuron40_trap_detection": {"title": "Trap Detection", "group": "pro", "stage": "pro", "description": "Deteksi bull trap dan bear trap."},
    "neuron11_long_setup": {"title": "Long Setup", "group": "setup", "stage": "setup", "description": "Validasi setup long."},
    "neuron12_short_setup": {"title": "Short Setup", "group": "setup", "stage": "setup", "description": "Validasi setup short."},
    "neuron13_breakout_retest": {"title": "Breakout Retest", "group": "setup", "stage": "setup", "description": "Entry continuation breakout."},
    "neuron14_pullback_reversal": {"title": "Pullback Reversal", "group": "setup", "stage": "setup", "description": "Pullback sehat vs reversal."},
    "neuron22_trend_continuation": {"title": "Trend Continuation", "group": "setup", "stage": "setup", "description": "Kelanjutan trend yang sehat."},
    "neuron23_range_fade": {"title": "Range Fade", "group": "setup", "stage": "setup", "description": "Fade di tepi range."},
    "neuron41_execution_location": {"title": "Execution Location", "group": "setup", "stage": "setup", "description": "Efisiensi lokasi entry."},
    "neuron15_confluence_score": {"title": "Confluence Score", "group": "setup", "stage": "setup", "description": "Skor kualitas setup."},
    "neuron42_drawdown_guard": {"title": "Drawdown Guard", "group": "risk", "stage": "risk", "description": "Risk mode saat akun drawdown."},
    "neuron53_compounding_drive": {"title": "Compounding Drive", "group": "adaptive", "stage": "adaptive", "description": "Menambah tekanan hanya saat pair benar-benar sinkron."},
    "neuron54_survival_instinct": {"title": "Survival Instinct", "group": "adaptive", "stage": "adaptive", "description": "Rem alami saat pair atau akun masuk fase berbahaya."},
    "neuron16_risk_budget": {"title": "Risk Budget", "group": "risk", "stage": "risk", "description": "Alokasi risk per trade."},
    "neuron71_risk_compression": {"title": "Risk Compression", "group": "cortex", "stage": "cortex", "description": "Kelayakan risk aktif untuk setup kelas atas."},
    "neuron43_recovery_mode": {"title": "Recovery Mode", "group": "risk", "stage": "risk", "description": "Mode pemulihan setelah loss streak."},
    "neuron26_position_sizing": {"title": "Position Sizing", "group": "risk", "stage": "risk", "description": "Multiplier size posisi."},
    "neuron44_account_heat": {"title": "Account Heat", "group": "risk", "stage": "risk", "description": "Jarak ke batas loss harian."},
    "neuron27_leverage_guard": {"title": "Leverage Guard", "group": "risk", "stage": "risk", "description": "Rem leverage agresif."},
    "neuron17_stop_loss_architect": {"title": "Stop Loss Architect", "group": "risk", "stage": "risk", "description": "Desain stop loss logis."},
    "neuron18_target_engine": {"title": "Target Engine", "group": "risk", "stage": "risk", "description": "Desain target profit."},
    "neuron45_asymmetry": {"title": "Asymmetry", "group": "risk", "stage": "risk", "description": "Asimetri risk-reward."},
    "neuron20_event_sentiment_guard": {"title": "Event Sentiment", "group": "risk", "stage": "risk", "description": "News dan macro risk filter."},
    "neuron31_correlation_context": {"title": "Correlation Context", "group": "risk", "stage": "risk", "description": "Korelasi market terhadap bias."},
    "neuron19_no_trade_filter": {"title": "No Trade Filter", "group": "risk", "stage": "risk", "description": "Filter keras untuk no-trade."},
    "neuron55_anti_overfit_filter": {"title": "Anti Overfit Filter", "group": "adaptive", "stage": "adaptive", "description": "Mencegah engine terlalu percaya pada histori yang masih tipis."},
    "neuron46_conviction_calibration": {"title": "Conviction Calib", "group": "risk", "stage": "risk", "description": "Kalibrasi ulang conviction."},
    "neuron56_confidence_memory": {"title": "Confidence Memory", "group": "adaptive", "stage": "adaptive", "description": "Menggeser confidence berdasarkan kedewasaan memori."},
    "neuron75_loss_review": {"title": "Loss Review", "group": "adaptive", "stage": "adaptive", "description": "Menaikkan disiplin saat replay loss menunjukkan pola berbahaya."},
    "neuron76_daily_coach": {"title": "Daily Coach", "group": "adaptive", "stage": "adaptive", "description": "Pelatih harian yang menyesuaikan confidence dan risk cap."},
    "neuron57_self_reflection": {"title": "Self Reflection", "group": "adaptive", "stage": "adaptive", "description": "Merangkum fase belajar aktif dari brain."},
    "neuron21_output_formatter": {"title": "Output Formatter", "group": "output", "stage": "output", "description": "Merapikan output final."},
    "neuron22_verdict_gate": {"title": "Verdict Gate", "group": "output", "stage": "output", "description": "Keputusan final LONG, SHORT, WAIT, atau NO TRADE."},
}


for neuron in ALL_NEURONS:
    meta = BASE_VISUAL_META.get(neuron.name, {})
    setattr(neuron, "title", getattr(neuron, "title", meta.get("title", neuron.name.replace("_", " ").title())))
    setattr(neuron, "visual_group", getattr(neuron, "visual_group", meta.get("group", "risk")))
    setattr(neuron, "visual_stage", getattr(neuron, "visual_stage", meta.get("stage", "risk")))
    setattr(neuron, "description", getattr(neuron, "description", meta.get("description", neuron.name)))
